# Generated by Django 3.2.13 on 2022-05-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('FatherName', models.CharField(max_length=50)),
                ('ClassName', models.IntegerField()),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
