# Generated by Django 3.2.13 on 2022-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('exp', models.IntegerField()),
                ('subject', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
